//
//  NewsInteractor.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsInteractor: NewsInteractorProtocol {

    weak var presenter: NewsPresenterProtocol?
}
