//
//  NewsRouter.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsRouter: NewsWireframeProtocol {
    
    weak var viewController: UIViewController?
    var baseViewController: UIViewController?
    
    class func createModule(viewController: NewsViewController) {
        let interactor = NewsInteractor()
        let router = NewsRouter()
        let presenter = NewsPresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
        router.baseViewController = viewController
    }
}
