//
//  NewsViewController.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsViewController: UIViewController, NewsViewProtocol {

	var presenter: NewsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        NewsRouter.createModule(viewController: self)
        presenter?.start()
    }
}
