//
//  NewsProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NewsWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol NewsPresenterProtocol: class {
    func start()
}

//MARK: Interactor -
protocol NewsInteractorProtocol: class {
    var presenter: NewsPresenterProtocol?  { get set }
    func start()
}

//MARK: View -
protocol NewsViewProtocol: class {
    
    var presenter: NewsPresenterProtocol?  { get set }
}
