//
//  DialogRouter.swift
//  VK Tosters
//
//  Created programmist_np on 01/02/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DialogRouter: DialogWireframeProtocol {
    
    weak var viewController: UIViewController?
    var baseViewController: UIViewController?
    
    class func createModule(viewController: DialogViewController) {
        let interactor = DialogInteractor()
        let router = DialogRouter()
        let presenter = DialogPresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
        router.baseViewController = viewController
    }
}
