//
//  DialogProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 01/02/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import SwiftyJSON

//MARK: Wireframe -
protocol DialogWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol DialogPresenterProtocol: class {
    func start(userId: String, offset: String)
    func onLoaded()
    func onSended()
    func onEvent(message: String, _ style: ToastStyle)
    func onSend(message: String, peerId: String)
    func getDialogMessage(indexPath: IndexPath) -> DialogMessageModel
    func getMessagesCount() -> Int
    func getAllMessagesCount() -> Int
}

//MARK: Interactor -
protocol DialogInteractorProtocol: class {
    var presenter: DialogPresenterProtocol?  { get set }
    var dialogMessagesJSON: [JSON] { get }
    var countJSON: Int { get }
    func start(userId: String, offset: String)
    func sendMessage(message: String, peerId: String)
}

//MARK: View -
protocol DialogViewProtocol: class {
    var presenter: DialogPresenterProtocol?  { get set }
    func reload()
    func clearTextView()
    func getToast(message: String, _ style: ToastStyle)
}
