//
//  ProfileInteractor.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
import SwiftyVK
import SwiftyJSON
import Realm
import RealmSwift

class ProfileInteractor: ProfileInteractorProtocol {

    weak var presenter: ProfilePresenterProtocol?
    var user: [JSON] = []
    
    func start(userId: String) {
        VK.API.Users.get([.userId: userId, .fields: ApiUsersFields.getUsersField])
            .configure(with: Config.init(httpMethod: .POST, language: Language(rawValue: "ru")))
            .onSuccess { response in
                self.user = JSON(response).arrayValue
                self.handleDataLoad(user: self.user)
                DispatchQueue.main.async {
                    let mapItems = self.user.map { User(jsonFullUser: $0) }
                    self.presenter?.onRequestSend(isLoaded: true)
                    self.presenter?.onDataLoad(user: mapItems[0], hasError: false, JSON: response)
                }
        }
        .onError { error in
            DispatchQueue.main.async {
                self.presenter?.onRequestSend(isLoaded: true)
                self.presenter?.onDataLoad(user: nil, hasError: true, JSON: nil)
            }
        }
        .send()
    }
    
    func handleDataLoad(user: [JSON]) {
        
    }
}
