//
//  ProfileProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import SwiftyJSON

//MARK: Wireframe -
protocol ProfileWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol ProfilePresenterProtocol: class {
    func start(userId: String)
    func onDataLoad(user: User?, hasError: Bool, JSON: Data?)
    func onRequestSend(isLoaded: Bool)
    func onEvent(message: String, _ style: ToastStyle)
}

//MARK: Interactor -
protocol ProfileInteractorProtocol: class {
    var presenter: ProfilePresenterProtocol?  { get set }
    func start(userId: String)
}

//MARK: View -
protocol ProfileViewProtocol: class {
    var presenter: ProfilePresenterProtocol?  { get set }
    static var userId: String { get }
    func setData(model: User, JSON: Data)
    func showErrorView()
    func hideErrorView()
    func showLoadingView()
    func hideLoadingView()
    func getToast(message: String, _ style: ToastStyle)
}
