//
//  ProfileProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import SwiftyJSON

//MARK: Wireframe -
protocol ProfileWireframeProtocol: class {
    func openFriends(userId: String)
}
//MARK: Presenter -
protocol ProfilePresenterProtocol: class {
    func start(userId: String)
    func onDataLoad(user: User?, hasError: Bool)
    func onRequestSend(isLoaded: Bool)
    func onEvent(message: String, _ style: ToastStyle)
    func onPhotoLoad(hasError: Bool)
    func onTapFriends(userId: String)
    func onTapToFriendAction(userId: String, friendStatus: Int)
    func getPhoto(indexPath: IndexPath) -> Photo
    func getPhotosCount() -> Int
    func getUser() -> User
}

//MARK: Interactor -
protocol ProfileInteractorProtocol: class {
    var presenter: ProfilePresenterProtocol?  { get set }
    var photos: [JSON] { get }
    var user: JSON { get }
    var userModel: User! { get }
    func start(userId: String)
    func getPhotos(ownerId: String, albumId: String)
    func addToFriends(userId: String)
    func deleteToFriends(userId: String)
}

//MARK: View -
protocol ProfileViewProtocol: class {
    var presenter: ProfilePresenterProtocol?  { get set }
    static var userId: String { get }
    func setData(model: User)
    func reloadCollection()
    func showErrorView(errorText: String)
    func hideErrorView()
    func showLoadingView()
    func hideLoadingView()
    func getToast(message: String, _ style: ToastStyle)
}
