//
//  ProfilePresenter.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SwiftyJSON

class ProfilePresenter: ProfilePresenterProtocol {

    weak private var view: ProfileViewProtocol?
    var interactor: ProfileInteractorProtocol?
    private let router: ProfileWireframeProtocol

    init(interface: ProfileViewProtocol, interactor: ProfileInteractorProtocol?, router: ProfileWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func start(userId: String) {
        interactor?.start(userId: userId)
    }
    
    func onDataLoad(user: User?, hasError: Bool, JSON: Data?) {
        if !hasError {
            view?.hideErrorView()
            view?.setData(model: user!, JSON: JSON!)
        } else {
            view?.showErrorView()
        }
    }
    
    func onRequestSend(isLoaded: Bool) {
        if isLoaded {
            view?.hideLoadingView()
        } else {
            view?.showLoadingView()
        }
    }
    
    func onEvent(message: String, _ style: ToastStyle) {
        view?.getToast(message: message, style)
    }
}
