//
//  ProfileViewController.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Kingfisher

class ProfileViewController: UIViewController, ProfileViewProtocol {
    @IBOutlet weak var photoProfile: UIImageView!
    @IBOutlet weak var profileLabel: UILabel!
    
	var presenter: ProfilePresenterProtocol?
    
    static var userId: String = ""

	override func viewDidLoad() {
        super.viewDidLoad()
        ProfileRouter.createModule(viewController: self)
        presenter?.start(userId: ProfileViewController.userId)
        setup()
    }
    
    func setData(model: User) {
        photoProfile.kf.setImage(with: URL(string: model.photoOriginal))
        profileLabel.text = model.name
    }
    
    func setup() {
        profileLabel.font = UIFont(name: "Lato-Bold", size: 18)
        profileLabel.textColor = Colors.shared.black
    }
}
