//
//  ProfileRouter.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileRouter: ProfileWireframeProtocol {
    
    weak var viewController: ProfileViewProtocol?
    var baseViewController: UIViewController?
    
    class func createModule(viewController: ProfileViewController) {
        let interactor = ProfileInteractor()
        let router = ProfileRouter()
        let presenter = ProfilePresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
        router.baseViewController = viewController
    }
    
    func openFriends(userId: String) {
        let friendsViewController = FriendsViewController(nibName: "FriendsViewController", bundle: nil)
        friendsViewController.modalPresentationStyle = .fullScreen
        FriendsViewController.userId = userId
        self.baseViewController?.performSegue(withIdentifier: "toFriendsFromProfile", sender: self)
    }
}
