//
//  ProfileInteractor.swift
//  VK Tosters
//
//  Created programmist_np on 22/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
import SwiftyVK
import SwiftyJSON

class ProfileInteractor: ProfileInteractorProtocol {

    weak var presenter: ProfilePresenterProtocol?
    var user: [JSON] = []
    
    func start(userId: String) {
        VK.API.Users.get([.userId: userId, .fields: ApiUsersFields.getUsersField])
            .configure(with: Config.init(httpMethod: .POST, language: Language(rawValue: "ru")))
            .onSuccess { response in
                self.user = JSON(response).arrayValue
                self.handleDataLoad(user: self.user)
        }
        .onError { error in
            print(error.localizedDescription)
        }
        .send()
    }
    
    func handleDataLoad(user: [JSON]) {
        DispatchQueue.main.async {
            let mapItems = user.map { User(json: $0) }
            self.presenter?.onDataLoad(user: mapItems[0])
        }
    }
}
