//
//  FriendsInteractor.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
import SwiftyVK
import SwiftyJSON

struct Response {
    let count: Int
    let items: [Friend]
}

class FriendsInteractor: FriendsInteractorProtocol {
    weak var presenter: FriendsPresenterProtocol?
    let fields: String = "nickname, domain, sex, bdate, city, country, timezone, photo_50, photo_100, photo_200_orig, has_mobile, contacts, education, online, relation, last_seen, status, can_write_private_message, can_see_all_posts, can_post, universities"
    
    func start() {
        VK.API.Friends.get([.count: String(50), .fields: fields])
            .configure(with: Config.init(httpMethod: .POST, language: Language(rawValue: "ru")))
            .onSuccess { response in
                self.handleResponse(response: JSON(response))
                DispatchQueue.main.async {
                    self.presenter?.onEvent(message: "Success", .default)
                }
        }
        .onError { error in
            DispatchQueue.main.async {
                self.presenter?.onEvent(message: "Error", .error)
            }
        }
        .send()
    }
    
    func handleResponse(response: JSON) {
        DispatchQueue.main.async {
            let json = response["items"].arrayValue
            let friends = json.map { Friend(json: $0) }
            print(friends)
        }
    }
}
