//
//  FriendsProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import SwiftyJSON

//MARK: Wireframe -
protocol FriendsWireframeProtocol: class {
    func openProfile(userId: String)
}
//MARK: Presenter -
protocol FriendsPresenterProtocol: class {
    func start(userId: String)
    func onEvent(message: String, _ style: ToastStyle)
    func onLoadData(hasError: Bool)
    func onTapUser(indexPath: IndexPath, isOnlineSegment: Bool)
    func onSwipeUser(indexPath: IndexPath, isOnlineSegment: Bool, completion: DeleteFriendCompletionHandler?)
    func onRequestSend(isLoaded: Bool)
    func getFriend(indexPath: IndexPath) -> Friend
    func getFriends() -> [Friend]
    func getOnlineFriends() -> [Friend]
    func getFriendsCount() -> Int
    func getName(nameCase: NameCases, indexPath: IndexPath, isOnlineSegment: Bool)
    func getUserIdBy(indexPath row: IndexPath, isOnlineSegment: Bool) -> String
}

//MARK: Interactor -
protocol FriendsInteractorProtocol: class {
    var presenter: FriendsPresenterProtocol?  { get set }
    var friendsJSON: [JSON] { get }
    func start(userId: String)
    func getNameWithCase(nameCase: NameCases, userId: String, completionHandler: GetUserNameHandler?)
    func deleteFriendsRequest(userId: String, completionHandler: DeleteFriendHandler?)
}

//MARK: View -
protocol FriendsViewProtocol: class {
    var presenter: FriendsPresenterProtocol?  { get set }
    func getToast(message: String, _ style: ToastStyle)
    func reloadTableView()
    func showErrorView()
    func hideErrorView()
    func showLoadingView()
    func hideLoadingView()
    func openPopup(headerText: String, descriptionText: String, confrimText: String?, declineText: String?)
}
