//
//  FriendsRouter.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FriendsRouter: FriendsWireframeProtocol {
    
    weak var viewController: FriendsViewProtocol?
    
    class func createModule(viewController: FriendsViewProtocol) {
        let interactor = FriendsInteractor()
        let router = FriendsRouter()
        let presenter = FriendsPresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
    }
}
