//
//  FriendsRouter.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FriendsRouter: FriendsWireframeProtocol {
    
    weak var viewController: FriendsViewProtocol?
    var baseViewController: UIViewController? {
        didSet {
            print("")
        }
    }
    
    static func createModule(viewController: FriendsViewController) {
        let interactor = FriendsInteractor()
        let router = FriendsRouter()
        let presenter = FriendsPresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
        router.baseViewController = viewController
    }
    
    func openProfile(userId: String, nameWithGenCase: String) {
        let profileViewController = ProfileViewController(nibName: "ProfileViewController", bundle: nil)
        ProfileViewController.userId = userId
        ProfileViewController.nameWithGenCase = nameWithGenCase
        self.baseViewController?.present(profileViewController, animated: true, completion: nil)
    }
}
