//
//  FriendsProtocols.swift
//  VK Tosters
//
//  Created programmist_np on 21/01/2020.
//  Copyright © 2020 programmist_np. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import SwiftyJSON

//MARK: Wireframe -
protocol FriendsWireframeProtocol: class {
    func openProfile(userId: Int)
}
//MARK: Presenter -
protocol FriendsPresenterProtocol: class {
    func start()
    func onEvent(message: String, _ style: ToastStyle)
    func onLoadData()
    func onTapUser(indexPath: IndexPath)
    func getFriend(indexPath: IndexPath) -> Friend
    func getFriendsCount() -> Int
}

//MARK: Interactor -
protocol FriendsInteractorProtocol: class {
    var presenter: FriendsPresenterProtocol?  { get set }
    var friendsJSON: [JSON] { get }
    func start()
}

//MARK: View -
protocol FriendsViewProtocol: class {
    var presenter: FriendsPresenterProtocol?  { get set }
    func showToast(message: String, _ style: ToastStyle)
    func reloadTableView()
}
